version: '3.4'

services:
  db:
    image: mysql:5.7
    container_name: twofactor_api_db
    environment:
      MYSQL_DATABASE: twofactor_api
      MYSQL_ROOT_PASSWORD: password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 13306:3306

  redis:
    image: redis:latest
    container_name: twofactor_api_redis
    ports:
      - 16379:6379
#    volumes:
#      - C:\temp\redis:/data