app:
  app-id: '@project.name@'
  app-name: '@project.description@'
  version: '@project.version@'

google:
  recaptcha:
    key:
      site: 6Ldv_9IUAAAAALEfEVkPxP884AJOh_rETKR_hXz2
      secret: 6Ldv_9IUAAAAAIwphyVtuWfhZ7OvSzUvlrhKEY60
  
spring:
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ssXXX"
    time-zone: "Asia/Tokyo"

  profiles:
    active:
      - develop